apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtransactional
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springtransactional
  template:
    metadata:
      labels:
        app: springtransactional
    spec:
      containers:
        - name: springtransactional
          image: badrinathwrk/springtransactional:springtransactional
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

apiVersion: v1
kind: Service
metadata:
  name: springtransactional
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springtransactional
